// Generated by scripts/build-ds-bundle.mjs — do not edit.

interface Window {
  TidepoolDesignSystem_8a0ead: {
    Button: typeof import("../design-system/components/actions/Button").Button;
    IconButton: typeof import("../design-system/components/actions/IconButton").IconButton;
    AgentChip: typeof import("../design-system/components/board/AgentChip").AgentChip;
    IdChip: typeof import("../design-system/components/board/IdChip").IdChip;
    LogEntry: typeof import("../design-system/components/board/LogEntry").LogEntry;
    QueueItem: typeof import("../design-system/components/board/QueueItem").QueueItem;
    RiskFlag: typeof import("../design-system/components/board/RiskFlag").RiskFlag;
    StatusBadge: typeof import("../design-system/components/board/StatusBadge").StatusBadge;
    TaskCard: typeof import("../design-system/components/board/TaskCard").TaskCard;
    TypeBadge: typeof import("../design-system/components/board/TypeBadge").TypeBadge;
    Checkbox: typeof import("../design-system/components/forms/Checkbox").Checkbox;
    FieldRow: typeof import("../design-system/components/forms/FieldRow").FieldRow;
    Input: typeof import("../design-system/components/forms/Input").Input;
    Select: typeof import("../design-system/components/forms/Select").Select;
    Switch: typeof import("../design-system/components/forms/Switch").Switch;
    NavRow: typeof import("../design-system/components/navigation/NavRow").NavRow;
    ScreenHeader: typeof import("../design-system/components/navigation/ScreenHeader").ScreenHeader;
    Card: typeof import("../design-system/components/surfaces/Card").Card;
    FadeScroll: typeof import("../design-system/components/surfaces/FadeScroll").FadeScroll;
    Dialog: typeof import("../design-system/components/surfaces/Dialog").Dialog;
    Tag: typeof import("../design-system/components/surfaces/Tag").Tag;
    Toast: typeof import("../design-system/components/surfaces/Toast").Toast;
  };
}

// public/vendor/lucide.js の UMD グローバル。
declare const lucide: typeof import("lucide");
